usuarios/applications/home/urls.py
from django.urls import path
from . import views
app_name = "home_app"

urlpatterns = [
    path('home/', views.HomePage.as_view(), name="home_page"),
    path('mixin/', views.PruebaMixin.as_view(), name="mixin"),
]

usuarios/applications/users/urls.py
from django.urls import path
from . import views
app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterCreateView.as_view(), name="register_user"),
    path('login/', views.LoginUser.as_view(), name="login_user"),
    path('logout/', views.LogoutView.as_view(), name="logout_user"),
    path('update/', views.UpdatePassword.as_view(), name="update_user"),
    path('verification/<pk>/', views.CodeVer.as_view(), name="verification_user"),

]

usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
]

usuarios/applications/home/models.py
from django.db import models

# Create your models here.

usuarios/applications/home/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView

# Create your views here.

class FechaMixin(object):
    
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context
    
class HomePage(LoginRequiredMixin, TemplateView):
    template_name = "home/index.html"
    login_url = reverse_lazy("users_app:login_user")

class PruebaMixin(FechaMixin, TemplateView):
    template_name = "home/mixin.html"
  

usuarios/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Panel de usuarios</h1>
    <h3>Bienvenido: {{user}}</h3>
    <ul>
        <li><a href="{% url 'users_app:logout_user' %}">Cerrar sesion</a></li>
        <li><a href="{% url 'users_app:update_user' %}">Actualizar datos</a></li>
    </ul>
    
</body>
</html>

usuarios/templates/home/mixin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Probando Mixin</h1>
    {{fecha}}
</body>
</html>